src/controllers/TicketzOSSController.ts(48,22): error TS2339: Property 'tagName' does not exist on type '{ commitHash: string; branchName: string; buildTimestamp: string; }'.